(function(){
'use strict';
var KEY='barbellScaleV2';
var base={profile:{name:'Cameron',calories:2400,water:128},workouts:[],meals:[],water:[],weights:[],pending:null,chat:[{role:'bot',text:'I’m Spotter. Tell me what you lifted, ate, drank, or weighed.'}]};
var db=load();
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{var old=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('barbellScaleV1')||'{}');return Object.assign(clone(base),old,{profile:Object.assign({},base.profile,old.profile||{})})}catch(e){return clone(base)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function el(id){return document.getElementById(id)}
function num(v){v=Number(v);return isFinite(v)?v:0}
function day(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function now(){return new Date().toISOString()}
function today(x){return x.date===day()}
function toast(t){el('toast').textContent=t;el('toast').classList.add('show');setTimeout(function(){el('toast').classList.remove('show')},1600)}
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function nav(name){document.querySelectorAll('.screen').forEach(function(s){s.classList.toggle('active',s.dataset.screen===name)});document.querySelectorAll('nav button').forEach(function(b){b.classList.toggle('active',b.dataset.nav===name)});scrollTo(0,0)}
function addWater(v){v=num(v);if(!v){toast('Enter water ounces');return false}db.water.push({date:day(),oz:v,at:now()});save();toast(v+' oz logged');return true}
function addWeight(v){v=num(v);if(!v){toast('Enter your weight');return false}db.weights.push({date:day(),weight:v,at:now()});save();toast(v+' lb logged');return true}
function addSet(){var name=el('exerciseName').value.trim(),w=num(el('exerciseWeight').value),r=num(el('exerciseReps').value),notes=el('exerciseNotes').value.trim();if(!name||!r)return toast('Add exercise and reps');db.workouts.push({date:day(),exercise:name,weight:w,reps:r,notes:notes,at:now()});el('exerciseReps').value='';save();toast('Set logged')}
function addMeal(){var name=el('mealName').value.trim();if(!name)return toast('Name the food');db.meals.push({date:day(),name:name,calories:num(el('mealCalories').value),protein:num(el('mealProtein').value),at:now()});['mealName','mealCalories','mealProtein'].forEach(function(id){el(id).value=''});save();toast('Meal logged')}
function remove(type,at){db[type]=db[type].filter(function(x){return x.at!==at});save()}
function summary(){var sets=db.workouts.filter(today).length,water=db.water.filter(today).reduce(function(a,x){return a+x.oz},0);if(!sets)return'Start with one solid set and build momentum.';if(water<db.profile.water/2)return'Good work. Now get some water in.';return'You are on track. Keep stacking wins.'}
function render(){var sets=db.workouts.filter(today),meals=db.meals.filter(today),water=db.water.filter(today).reduce(function(a,x){return a+x.oz},0),cal=meals.reduce(function(a,x){return a+x.calories},0),latest=db.weights.length?db.weights[db.weights.length-1]:null;el('homeName').textContent=db.profile.name;el('homeSets').textContent=sets.length;el('homeCalories').textContent=cal;el('homeWater').textContent=water+' oz';el('homeWeight').textContent=latest?latest.weight+' lb':'—';el('spotterSummary').textContent=summary();el('todaySets').innerHTML=sets.length?sets.slice().reverse().map(function(x){return'<div class="item"><div><b>'+esc(x.exercise)+'</b><br><small>'+(x.weight?x.weight+' lb × ':'')+x.reps+' reps'+(x.notes?' · '+esc(x.notes):'')+'</small></div><button data-remove="workouts" data-at="'+x.at+'">×</button></div>'}).join(''):'<div class="item"><small>No sets logged today.</small></div>';el('mealList').innerHTML=meals.length?meals.slice().reverse().map(function(x){return'<div class="item"><div><b>'+esc(x.name)+'</b><br><small>'+x.calories+' cal · '+x.protein+'g protein</small></div><button data-remove="meals" data-at="'+x.at+'">×</button></div>'}).join(''):'<div class="item"><small>No meals logged today.</small></div>';el('chatLog').innerHTML=db.chat.slice(-30).map(function(x){return'<div class="bubble '+x.role+'">'+esc(x.text)+'</div>'}).join('');el('chatLog').scrollTop=el('chatLog').scrollHeight;el('progressSets').textContent=db.workouts.length;el('progressDays').textContent=new Set(db.workouts.map(function(x){return x.date})).size;el('weightHistory').innerHTML=db.weights.length?db.weights.slice().reverse().map(function(x){return'<div class="item"><div><b>'+x.weight+' lb</b><br><small>'+x.date+'</small></div><button data-remove="weights" data-at="'+x.at+'">×</button></div>'}).join(''):'<div class="item"><small>No weight entries yet.</small></div>';el('profileName').value=db.profile.name;el('goalCalories').value=db.profile.calories;el('goalWater').value=db.profile.water}
function title(s){return s.replace(/\b\w/g,function(c){return c.toUpperCase()})}
function foodFollowup(text){var m=text.match(/(\d+(?:\.\d+)?)\s*(?:cal|calories)/i);if(m&&db.pending&&db.pending.type==='meal'){var total=num(m[1]);db.meals.push({date:day(),name:db.pending.name,calories:total,protein:0,at:now()});var n=db.pending.name;db.pending=null;return'Perfect — I logged '+n+' for '+total+' calories.'}return null}
function command(text){var l=text.toLowerCase().trim(),m,follow=foodFollowup(text);if(follow)return follow;
if(/^(hi|hello|hey|yo|good morning|good afternoon|good evening)[!. ]*$/.test(l))return'Hey '+db.profile.name+'! I’m ready. Tell me what you ate, drank, weighed, or lifted.';
if(l.indexOf('thank')>=0)return'You got it. Keep them coming.';
if(l.indexOf('how am i doing')>=0||l.indexOf('progress')>=0)return summary();
m=l.match(/(\d+(?:\.\d+)?)\s*(?:oz|ounces)/);if(m){db.water.push({date:day(),oz:num(m[1]),at:now()});return'Logged '+m[1]+' oz of water.'}
m=l.match(/(?:weigh|weight|weighed).*?(\d{2,3}(?:\.\d+)?)/);if(m){db.weights.push({date:day(),weight:num(m[1]),at:now()});return'Logged your weight at '+m[1]+' lb.'}
m=l.match(/(\d+(?:\.\d+)?)\s*(?:lb|lbs|pounds).*?(\d+)\s*(?:reps?|times).*?(?:on|of)?\s*([a-z].*)/);if(m){var exercise=title(m[3].replace(/^on\s+|^of\s+/,''));db.workouts.push({date:day(),exercise:exercise,weight:num(m[1]),reps:num(m[2]),notes:'Spotter log',at:now()});return'Logged '+m[1]+' lb for '+m[2]+' reps on '+exercise+'.';}
m=l.match(/(?:i\s+)?(?:ate|had|eating)\s+(.+)/);if(m){var food=m[1].replace(/[.!]$/,'').trim(),cal=l.match(/(\d+(?:\.\d+)?)\s*(?:cal|calories)/);if(cal){db.meals.push({date:day(),name:title(food.replace(/\s+(?:for|at)\s+\d+.*$/,'')),calories:num(cal[1]),protein:0,at:now()});return'Logged '+food+' at '+cal[1]+' calories.'}db.pending={type:'meal',name:title(food)};return'Got it — '+food+'. About how many calories was that total? You can reply with something like “300 calories.”';}
if(l.indexOf('sore')>=0)return'If it is normal muscle soreness, keep today lighter and focus on good movement, hydration, protein, and sleep. Sharp or worsening pain is a reason to stop that movement.';
if(l.indexOf('workout')>=0)return'Tell me the exercise, weight, and reps, and I’ll log each set. Example: “165 pounds for 7 reps on bench press.”';
return'I’m with you. I can log normal phrases about food, water, weight, and workouts. Tell me what you did, and I’ll ask a follow-up when I need one.'}
function send(){var t=el('chatInput').value.trim();if(!t)return;db.chat.push({role:'user',text:t});var reply=command(t);db.chat.push({role:'bot',text:reply});el('chatInput').value='';save()}
document.addEventListener('click',function(e){var n=e.target.closest('[data-nav]');if(n)return nav(n.dataset.nav);var r=e.target.closest('[data-remove]');if(r)return remove(r.dataset.remove,r.dataset.at)});
el('quickWaterButton').onclick=function(){if(addWater(el('quickWater').value))el('quickWater').value=''};el('quickWeightButton').onclick=function(){if(addWeight(el('quickWeight').value))el('quickWeight').value=''};el('addSetButton').onclick=addSet;el('addMealButton').onclick=addMeal;el('sendChatButton').onclick=send;el('chatInput').onkeydown=function(e){if(e.key==='Enter')send()};
el('saveProfileButton').onclick=function(){db.profile.name=el('profileName').value.trim()||'Athlete';db.profile.calories=num(el('goalCalories').value)||2400;db.profile.water=num(el('goalWater').value)||128;save();toast('Profile saved')};
el('exportButton').onclick=function(){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='barbell-scale-backup.json';a.click()};
el('resetButton').onclick=function(){if(confirm('Delete all saved data?')){localStorage.removeItem(KEY);db=clone(base);save()}};
el('voiceButton').onclick=function(){var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('Voice is not supported in this browser');var rec=new SR();rec.lang='en-US';el('voiceStatus').textContent='Listening…';rec.onresult=function(e){el('chatInput').value=e.results[0][0].transcript;send()};rec.onend=function(){el('voiceStatus').textContent='Tap to talk'};rec.start()};
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=3').catch(function(){})
})();
